name: deploy-app
on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Execute Server Command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AIRI_SSH_HOST }}
                  username: ${{ secrets.AIRI_SSH_USER }}
                  key: ${{ secrets.AIRI_SSH_PRIVATE_KEY }}
                  script: |
                      echo "SSH into the server"
                      whoami
                      ls
                      rm -rf izuna
                      git clone https://github.com/arung-agamani/izuna.git
                      cd izuna
                      docker build .
