name: deploy-app
on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.AIRI_SSH_PRIVATE_KEY }}
                  known_hosts: "awoo"
            - name: Add Known Host
              run: ssh-keyscan -H ${{ secrets.AIRI_SSH_HOST }}
            - name: Execute Server Command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AIRI_SSH_HOST }}
                  username: ${{ secrets.AIRI_SSH_USER }}
                  key: ${{ secrets.AIRI_SSH_PRIVATE_KEY }}
                  script: |
                      echo "SSH into the server"
                      whoami
